server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 12000
    frameBufferDurationMs: 12000
    youtubePlaylistLoadLimit: 20
    playerUpdateInterval: 3
    youtubeSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - TVHTML5_SIMPLY
      - WEB
      - ANDROID_VR
    oauth:
      enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: WARN
